; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27043.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Alex\Documents\GitHub\ASCII-Converter\x64\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
